### ISSUE TITLE
Missing QJsonObject

### ISSUE THREAD

**Issue by richardmoe** [BOSSoNe0013/track-o-bot#37]
Trying to compile on OpenSuse Tumbleweed with qt5.5: 

>❯ make
make -f Makefile.Debug
make[1]: Entering directory '/home/richard/Downloads/track-o-bot'
/usr/bin/uic src/ui/MainWindow.ui -o tmp/ui_MainWindow.h
/usr/bin/uic src/ui/SettingsWidget.ui -o tmp/ui_SettingsWidget.h
/usr/bin/uic src/ui/AccountWidget.ui -o tmp/ui_AccountWidget.h
/usr/bin/uic src/ui/LogWidget.ui -o tmp/ui_LogWidget.h
/usr/bin/uic src/ui/AboutWidget.ui -o tmp/ui_AboutWidget.h
g++ -pipe -g -D_REENTRANT -Wall -W -DVERSION=\"0.7.1\" -D_DEBUG -DPLATFORM=\"linux\" -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -Itmp -Itmp -x c++-header -c src/Local.h -o tmp/Track-o-Bot.gch/c++
g++ -c -include tmp/Track-o-Bot -pipe -g -D_REENTRANT -Wall -W -DVERSION=\"0.7.1\" -D_DEBUG -DPLATFORM=\"linux\" -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -Itmp -Itmp -o tmp/Main.o src/Main.cpp
In file included from src/HearthstoneLogTracker.h:4:0,
                 from src/ResultTracker.h:3,
                 from src/Trackobot.h:6,
                 from src/Main.cpp:1:
src/Result.h:5:23: fatal error: QJsonObject: No such file or directory
compilation terminated.
Makefile.Debug:375: recipe for target 'tmp/Main.o' failed
make[1]: *** [tmp/Main.o] Error 1
make[1]: Leaving directory '/home/richard/Downloads/track-o-bot'
Makefile:34: recipe for target 'debug' failed
make: *** [debug] Error 2


> ❯ ls -l /usr/include/qjson                                                                                                                                                                                                                               ⏎
total 32
-rw-r--r-- 1 root root 2946 Nov 27  2012 parser.h
-rw-r--r-- 1 root root 1900 Nov 27  2012 parserrunnable.h
-rw-r--r-- 1 root root 1118 Nov 27  2012 qjson_export.h
-rw-r--r-- 1 root root 4263 Nov 27  2012 qobjecthelper.h
-rw-r--r-- 1 root root 5276 Nov 27  2012 serializer.h
-rw-r--r-- 1 root root 2143 Nov 27  2012 serializerrunnable.h

[richard@linux-ykeh] ~/Downloads/track-o-bot (master)

**Comment by BOSSoNe0013** [comment]
Hi,
QJsonObject is include in Qt5 Core base  dev package, on Ubuntu it's in qtbase5-dev package (i don't know for Suse):
qtbase5-dev: /usr/include/x86_64-linux-gnu/qt5/QtCore/QJsonObject.h

Thanks
